spring.application.name=app

spring.datasource.url=jdbc:sqlite:worldturism.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

app.jwt.secret=VGhpcy1pcy1hLWRldi1zZWNyZXQtZm9yLXdvcmxkdHVyaXNtLWp3dC0zMi1ieXRlcy1taW4=
app.jwt.expiration-millis=86400000
